// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
const SupplyChain = artifacts.require('SupplyChain');
const truffleAssert = require('truffle-assertions');

contract('SupplyChain', function(accounts) {

    // Declare few constants and assign a few sample accounts generated by ganache-cli
    let sku = 1;
    let upc = 1;

    const productionID = 1;
    const ownerID = accounts[0];
    const farmerID = accounts[1];
    const millID = accounts[2];
    const shopID = accounts[3];
    const customerID = accounts[4];
    const unkownID = accounts[9];

    // Farm Test Data
    const farmerName = "Eifel Gold Oil Farm";
    const fieldName = "Goldfield";
    const latitude = "-38.239770";
    const longitude = "144.341490";

    // Mill Test Data
    const millName = "Eifel Small River Mill";
    const amountLiters = "10";
    const harvestTime = Date.now();
    const pressTime = Date.now()+10000;
    const bottlingTime = Date.now()+20000;


  const price = web3.utils.toWei('1', 'ether');

   /* let productID = sku + upc;

    */
    const emptyAddress = '0x00000000000000000000000000000000000000';

    console.log("ganache-cli accounts used here...");
    console.log("Contract Owner: accounts[0] ", ownerID);
    console.log("Farmer: accounts[1] ", farmerID);
    console.log("Mill: accounts[2] ", millID);
    console.log("Shop: accounts[3] ", shopID);
    console.log("Costumer: accounts[4] ", customerID);
    console.log("Unkown: accounts[9] ", unkownID);

    // 1st Test
    it("Testing smart contract function harvest that allows a farmer to harvest the seed", async() => {
        const callerID = ownerID;
        const supplyChain = await SupplyChain.deployed({from: callerID});
        await supplyChain.addFarmer(farmerID, {from: callerID});

        // Declare and Initialize a variable for event
        let eventEmitted = false;

        // Watch the emitted event Harvested()
        let event = await supplyChain.Harvested({}, (err, res) => {
            eventEmitted = true;
        });

        truffleAssert.reverts(supplyChain.harvest(productionID, farmerID, farmerName, harvestTime, fieldName,
        latitude, longitude, {from: unkownID}), null, 'Unkown can harvest!!');

        // Mark an item as Harvested by calling function harvestItem()
        await supplyChain.harvest(productionID, farmerID, farmerName, harvestTime, fieldName,
          latitude, longitude, {from: farmerID});

        // Retrieve farm data from oil production
        const result = await supplyChain.fetchOilProductionFarm.call(productionID, {from: callerID});

        // Verify the result set
        assert.equal(result[0], farmerID, 'Error: Missing or Invalid ownerID, Farmer is Owner of the OilProduction');
        assert.equal(result[1], farmerID, 'Error: Missing or Invalid farmerID');
        assert.equal(result[2], farmerName, 'Error: Missing or Invalid farmerName');
        assert.equal(result[3], harvestTime, 'Error: Missing or Invalid harvestTime');
        assert.equal(result[4], fieldName, 'Error: Missing or Invalid fieldName');
        assert.equal(result[5], latitude, 'Error: Missing or Invalid latitude');
        assert.equal(result[6], longitude, 'Error: Missing or Invalid longitude');
        assert.equal(result[7], 0, 'Error: Invalid OilProduction State');
        assert.equal(eventEmitted, true, 'Invalid event emitted');
    });


    // 2nd Test
    it("Testing the smart contract function press that allows a miller to press oil", async() => {
        const callerID = ownerID;
        const supplyChain = await SupplyChain.deployed({from: callerID});
        await supplyChain.addMill(millID, {from: callerID});

        // Declare and Initialize a variable for event
        let eventEmitted = false;

        // Watch the emitted event Harvested()
        let event = await supplyChain.Pressed({}, (err, res) => {
          eventEmitted = true;
        });

        truffleAssert.reverts(supplyChain.press(productionID, millID, millName, amountLiters, pressTime,
          {from: unkownID}), null, 'Unkown can press!!');

        // Mark an item as Harvested by calling function harvestItem()
        await supplyChain.press(productionID, millID, millName, amountLiters, pressTime, {from: millID});

        // Retrieve farm data from oil production
        const result = await supplyChain.fetchOilProduction.call(productionID, {from: callerID});

        // Verify the result set
        assert.equal(result[0], millID, 'Error: Missing or Invalid ownerID, Miller is Owner of the Oilproduction');
        assert.equal(result[1], millID, 'Error: Missing or Invalid millID');
        assert.equal(result[3], millName, 'Error: Missing or Invalid millName');
        assert.equal(result[4], pressTime, 'Error: Missing or Invalid pressTime');
        assert.equal(result[5], amountLiters, 'Error: Missing or Invalid amountLiters');
        assert.equal(result[10], 1, 'Error: Invalid item State');
        assert.equal(eventEmitted, true, 'Invalid event emitted');
    });

    // 3rd Test
    it("Testing the smart contract function bottling that enables a miller to bottle the oil", async() => {
        const callerID = ownerID;
        const supplyChain = await SupplyChain.deployed({from: callerID});
        // Declare and Initialize a variable for event
        let eventEmitted = false;

        // Watch the emitted event Harvested()
        let event = await supplyChain.Bottled({}, (err, res) => {
          eventEmitted = true;
        });

        truffleAssert.reverts(supplyChain.bottling(productionID, bottlingTime,
          {from: unkownID}), null, 'Unkown can press!!');

        // Mark an item as Harvested by calling function harvestItem()
        await supplyChain.bottling(productionID, bottlingTime, {from: millID});

        // Retrieve farm data from oil production
        const result = await supplyChain.fetchOilProduction.call(productionID, {from: callerID});

        // Verify the result set
        assert.equal(result[0], millID, 'Error: Missing or Invalid ownerID, Miller is Owner of the Oilproduction');
        assert.equal(result[1], millID, 'Error: Missing or Invalid millID');
        assert.equal(result[3], millName, 'Error: Missing or Invalid millName');
        assert.equal(result[4], pressTime, 'Error: Missing or Invalid pressTime');
        assert.equal(result[5], amountLiters, 'Error: Missing or Invalid amountLiters');
        assert.equal(result[6], bottlingTime, 'Error: Missing or Invalid bottlingDate');
        assert.equal(result[10], 2, 'Error: Invalid item State');
        assert.equal(eventEmitted, true, 'Invalid event emitted');

        



    });

    // 4th Test
    it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event ForSale()


        // Mark an item as ForSale by calling function sellItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 5th Test
    it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Sold()
        var event = supplyChain.Sold()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 6th Test
    it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Shipped()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 7th Test
    it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Received()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 8th Test
    it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Purchased()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 9th Test
    it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set:

    })

    // 10th Test
    it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async() => {
        const supplyChain = await SupplyChain.deployed()

        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set:

    })

});

